"""Exercise the current WorkflowPreview Vue component in isolated Edge."""
import base64
import json
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.request
from pathlib import Path

import websocket
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from agent_runtime import visual_acceptance as visual  # noqa: E402

_CREATION = getattr(subprocess, "CREATE_NO_WINDOW", 0)
CACHE = ROOT / "frontend" / ".docmind"
PAGE = CACHE / "workflow-preview-smoke.html"
PREVIEW = CACHE / "workflow-preview-test.html"
PIXEL = CACHE / "workflow-preview-pixel.png"
# 归属标记：守卫要区分「这是上一次本脚本被硬杀留下的垃圾」和「这是别人真放的夹具」。
# 只看存在性的话，一次中断就会永久毒死之后每一次运行，而且报错指向用户的意图而不是
# 三天前那次崩溃——最难查的那种。标记存在即认定三个文件是我们自己的，可以直接覆盖。
OWNED = CACHE / ".workflow-preview-smoke.owned"


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    CACHE.mkdir(parents=True, exist_ok=True)
    existing = [path.name for path in (PAGE, PREVIEW, PIXEL) if path.exists()]
    if existing and not OWNED.exists():
        raise RuntimeError("Refusing to overwrite an existing UI fixture: %s" % ", ".join(existing))
    OWNED.write_text("generated by workflow_preview_smoke.py", encoding="utf-8")
    process = None
    connection = None
    job = None
    with tempfile.TemporaryDirectory(prefix="docmind-workflow-preview-", ignore_cleanup_errors=True) as profile:
        try:
            shutil.copyfile(Path(__file__).with_suffix(".html"), PAGE)
            PREVIEW.write_text(
                '<html><meta charset="utf-8"><style>body{margin:0;background:#183655;color:white;font:18px Arial}'
                'button{display:block;width:200px;height:44px;border:0;background:#e84c4c;color:white}'
                'canvas{display:block;margin-top:26px}</style><body><h1>项目画面</h1><button>运行项目</button>'
                '<canvas width="200" height="60"></canvas><script>'
                'window.parent.previewLoads=(window.parent.previewLoads||0)+1;'
                'document.querySelector("button").style.background=localStorage.getItem("preview-smoke-color")||"#e84c4c";'
                'const c=document.querySelector("canvas").getContext("2d");c.fillStyle="#70aaff";c.fillRect(0,0,200,60)'
                '</script></body></html>',
                encoding="utf-8",
            )
            Image.new("RGB", (320, 180), "#183655").save(PIXEL)
            # 进程侧与 browser_session 共用同一份回收：浏览器被创建在 kill-on-close 作业
            # 对象里（出生即在内），脚本被硬杀时操作系统收走整棵树。
            # 注意这里只共享了「进程」那一半：profile 目录仍由外层 `with TemporaryDirectory`
            # 负责，它不带退避重试，所以 Edge 退出锁没放时可能留下一个空目录（该前缀不在
            # sweep 的回收范围内）。要补的话就是给 with 之后再调一次 _release_profile。
            process, job, spawn_error = visual.spawn_browser_in_job(
                [visual._edge_binary(), *visual._BASE_FLAGS,
                 f"--user-data-dir={profile}",
                 "--window-size=1440,1100", "about:blank"],
                _CREATION)
            if process is None:
                raise RuntimeError("浏览器未能创建在回收作业对象里：%s" % spawn_error)
            active = Path(profile) / "DevToolsActivePort"
            for _ in range(100):
                if active.exists():
                    break
                time.sleep(.1)
            if not active.exists():
                raise RuntimeError("Edge remote debugging did not start")
            port = active.read_text().splitlines()[0]
            with urllib.request.urlopen(f"http://127.0.0.1:{port}/json") as response:
                tabs = json.load(response)
            connection = websocket.create_connection(
                next(tab["webSocketDebuggerUrl"] for tab in tabs if tab["type"] == "page"),
                timeout=45, suppress_origin=True,
            )
            seq = 0

            def call(method, params=None):
                nonlocal seq
                seq += 1
                connection.send(json.dumps({"id": seq, "method": method, "params": params or {}}))
                while True:
                    message = json.loads(connection.recv())
                    if message.get("id") == seq:
                        if "error" in message:
                            raise RuntimeError(message["error"])
                        return message["result"]

            call("Page.enable")
            call("Runtime.enable")
            call("Page.navigate", {"url": "http://127.0.0.1:5179/.docmind/workflow-preview-smoke.html"})
            result = call("Runtime.evaluate", {
                "expression": "(async()=>{for(let i=0;i<150;i++){if(window.runSmoke)return await window.runSmoke();"
                              "await new Promise(r=>setTimeout(r,100))}throw new Error('UI did not load')})()",
                "awaitPromise": True, "returnByValue": True,
            })
            if "exceptionDetails" in result:
                raise RuntimeError(json.dumps(result["exceptionDetails"], ensure_ascii=False))
            print(json.dumps(result["result"]["value"], ensure_ascii=False, indent=2))
        finally:
            # 每一步单独尽力。原来 `connection.close()` 一抛异常，taskkill 和夹具的删除
            # 就一起被跳掉；泄漏还在其次——脚本自己留下的夹具如果不连归属标记一起删，
            # 下一次运行会被守卫挡住，那才是最难查的。
            def quiet(action):
                try:
                    action()
                except Exception:
                    pass

            quiet(lambda: connection and connection.close())
            # 先解绑作业（真正在干活的那一步），再尽力一试 taskkill：launcher 早已自行
            # 退出，taskkill 只会报 rc=128，不能把它当成就绪的证据。
            if job is not None:
                visual._close_reaper(job)
            if process:
                quiet(lambda: subprocess.run(
                    ["taskkill", "/PID", str(process.pid), "/T", "/F"],
                    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                    creationflags=_CREATION, timeout=10))
                # 等不到也不抛：解绑作业本身就是兜底，卡在这里反而把夹具删除拖没了。
                quiet(lambda: process.wait(timeout=10))
            for fixture in (PAGE, PREVIEW, PIXEL, OWNED):
                quiet(lambda path=fixture: path.unlink(missing_ok=True))
    # `with TemporaryDirectory` 自己那次删除不带退避重试：Edge 退出时还锁着自己的文件，
    # 一次失败就永久留下目录（实测正常退出也会留）。with 退出后再试一轮。
    visual._release_profile(profile)


if __name__ == "__main__":
    main()
