<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { agentApi } from '../api'
const open=ref(false), route=ref('local'), complexity=ref(0), auto=ref(false), connectors=ref<{key:string;label:string;enabled:boolean}[]>([]), externalPath=ref(''), approval=ref(false), msg=ref(''), approvals=ref<any[]>([])
async function load(){ try { const r=await agentApi.routing(); auto.value=!!r.auto_cloud_enabled; const c=await agentApi.connectors(); connectors.value=c.connectors||[]; approvals.value=(await agentApi.approvals()).approvals||[] } catch {} }
onMounted(load)
async function request(){ if(!externalPath.value)return; if(!approval.value){ const r=await agentApi.requestApproval([externalPath.value],'外部文件修改申请'); approvals.value.push(r.approval); msg.value='已创建审批请求'; return } const r=await agentApi.permission({path:externalPath.value,allow_external:true,approved:true}); msg.value=r.recorded?'已记录授权':(r.reason||'失败') }
async function decide(id:string,status:string){ await agentApi.decide(id,status); await load() }
window.addEventListener('docmind-agent-route',(e:any)=>{ route.value=e.detail?.route||'local'; complexity.value=e.detail?.complexity||0 })
</script>
<template><div class="ap"><button class="ap-trigger" :title="'AI 在哪运行：本地显卡 / 云端自动切换，以及对外操作授权'" @click="open=!open">AI 设置 · {{ route === 'local' ? '本地' : route }}</button><Teleport to="body"><div v-if="open" class="ap-backdrop" @click="open=false"></div><div v-if="open" class="ap-pop" role="dialog" aria-label="AI 设置"><b>AI 在哪运行</b><div>当前：{{ route === 'local' ? '本地显卡（免费）' : route }} · 本轮复杂度 {{ complexity }}</div><div>难题自动转云端：{{ auto?'已启用':'已关闭' }}</div><b style="margin-top:6px">外接工具</b><div v-if="!connectors.length" class="ap-empty">暂无外接工具（游戏引擎等在「AI 助手 → 游戏引擎」里连接）</div><div v-for="c in connectors" :key="c.key">{{ c.label||c.key }} · {{ c.enabled?'可用':'未启用' }}</div><b style="margin-top:6px">改项目外文件的授权</b><input v-model="externalPath" placeholder="项目文件夹之外的路径"/><label><input type="checkbox" v-model="approval"/> 我已确认，允许修改</label><button @click="request">提交授权</button><small>{{ msg }}</small><div v-for="a in approvals" :key="a.id" class="ap-approval"><div>{{ a.id }} · {{ a.status === 'pending' ? '待批准' : a.status }}</div><div>{{ a.summary }}</div><pre v-if="a.diff">{{ a.diff }}</pre><button v-if="a.status==='pending'" @click="decide(a.id,'approved')">批准</button><button v-if="a.status==='pending'" @click="decide(a.id,'rejected')">拒绝</button></div></div></Teleport></div></template>
<style scoped>.ap{position:relative}.ap-trigger{background:transparent;color:var(--text-muted);border:1px solid var(--border-strong);border-radius:5px;padding:5px 9px;cursor:pointer}.ap-trigger:hover{color:var(--text);border-color:var(--accent)}.ap-backdrop{position:fixed;inset:0;z-index:299;background:#0002}.ap-pop{position:fixed;right:16px;top:64px;max-height:calc(100vh - 90px);max-width:calc(100vw - 48px);overflow:auto;width:256px;padding:11px 12px;background:var(--bg-raised);border:1px solid var(--border-strong);border-radius:10px;box-shadow:0 14px 38px rgba(35,52,84,.2);z-index:300;font-size:11px;line-height:1.8}.ap-pop b{display:block;color:var(--text)}.ap-empty{color:var(--text-faint)}.ap-pop input[type=text],.ap-pop input:not([type]){width:100%;box-sizing:border-box;margin:3px 0;padding:5px 7px;background:var(--bg);border:1px solid var(--border);border-radius:5px;color:var(--text);font:inherit}.ap-pop label{display:flex;gap:5px;align-items:center;color:var(--text-muted)}.ap-pop button{margin-top:5px;background:linear-gradient(180deg,#3b7ef2,#2f6fed);border:1px solid #2560d4;color:#fff;border-radius:5px;padding:4px 11px;font-size:11px;cursor:pointer}.ap-pop small{display:block;color:var(--green);margin-top:3px}.ap-approval{margin-top:6px;padding:6px 8px;background:var(--bg-hover);border:1px solid var(--border);border-radius:6px}.ap-approval pre{max-height:90px;overflow:auto;margin:4px 0;font:10px var(--font-mono)}.ap-approval button{margin-right:6px}</style>
