<script setup lang="ts">
import { onMounted, ref } from 'vue'
const open=ref(false), route=ref('local'), complexity=ref(0), auto=ref(false), connectors=ref<{key:string;label:string;enabled:boolean}[]>([]), externalPath=ref(''), approval=ref(false), msg=ref(''), approvals=ref<any[]>([])
async function load(){ try { const r=await fetch('/api/agent/routing').then(x=>x.json()); auto.value=!!r.auto_cloud_enabled; const c=await fetch('/api/agent/connectors').then(x=>x.json()); connectors.value=c.connectors||[]; approvals.value=(await fetch('/api/agent/approvals').then(x=>x.json())).approvals||[] } catch {} }
onMounted(load)
async function request(){ if(!externalPath.value)return; if(!approval.value){ const r=await fetch('/api/agent/approvals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({paths:[externalPath.value],summary:'外部文件修改申请'})}).then(x=>x.json()); approvals.value.push(r.approval); msg.value='已创建审批请求'; return } const r=await fetch('/api/agent/permission',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:externalPath.value,allow_external:true,approved:true})}).then(x=>x.json()); msg.value=r.recorded?'已记录授权':(r.reason||'失败') }
async function decide(id:string,status:string){ await fetch('/api/agent/approvals/decide',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})}); await load() }
window.addEventListener('docmind-agent-route',(e:any)=>{ route.value=e.detail?.route||'local'; complexity.value=e.detail?.complexity||0 })
</script>
<template><div class="ap"><button class="ap-trigger" @click="open=!open">Agent · {{ route }}</button><div v-if="open" class="ap-pop"><b>模型策略</b><div>当前：{{ route }} · 复杂度 {{ complexity }}</div><div>自动云端：{{ auto?'已启用':'已关闭' }}</div><b>连接器</b><div v-for="c in connectors" :key="c.key">{{ c.label||c.key }} · {{ c.enabled?'可用':'未启用' }}</div><b>外部文件审批</b><input v-model="externalPath" placeholder="外部文件路径"/><label><input type="checkbox" v-model="approval"/> 已获用户批准</label><button @click="request">请求/记录</button><small>{{ msg }}</small><div v-for="a in approvals" :key="a.id" class="ap-approval"><div>{{ a.id }} · {{ a.status }}</div><div>{{ a.summary }}</div><pre v-if="a.diff">{{ a.diff }}</pre><button v-if="a.status==='pending'" @click="decide(a.id,'approved')">批准</button><button v-if="a.status==='pending'" @click="decide(a.id,'rejected')">拒绝</button></div></div></div></template>
<style scoped>.ap{position:relative}.ap-trigger{background:transparent;color:var(--text-muted);border:1px solid var(--border-strong);border-radius:5px;padding:5px 9px;cursor:pointer}.ap-pop{position:absolute;right:0;top:34px;width:240px;padding:10px;background:var(--bg-raised);border:1px solid var(--border-strong);border-radius:6px;z-index:30;font-size:11px;line-height:1.8}.ap-pop b{display:block;color:var(--text)}</style>
